### PR TITLE
Publish images to Amazon public ECR

### PR DESCRIPTION
**Pull request by rnishtala-sumo**
Issue: https://github.com/SumoLogic/sumologic-docker-logging-driver/issues/42

### CODE REVIEW

**Comment by rnishtala-sumo** [comment]
@samjsong should we bump up the version?, its only a change in the repository.

**Comment by rnishtala-sumo** [comment]
Another option is to leave the default repo as GHCR and just publish the 1.0.6 to ECR

**Review by vsinghal13 — COMMENTED** [review]
Based on the comments in the issue, I think we should make publishing to ECR as default. And, also publish to ghcr for existing customers who might still want to get updated version later on.

**Review by vsinghal13 — APPROVED** [review]

**Comment by samjsong** [comment]
Thank you Raj. IMO we shouldn’t bump the version since there was no change to the functionality of the logging driver

**Review by samjsong — APPROVED** [review]

**Comment by yermulnik** [comment]
Thanks a lot!

**Pull request merged**
